export const CHANGE_AUTHORIZAION = 'CHANGE_AUTHORIZAION'
export const CHANGE_FULLSCREEN = 'CHANGE_FULLSCREEN'

export const SAVE_ANSWER = 'SAVE_ANSWER'
export const SAVE_ANSWER_STATUS = 'SAVE_ANSWER_STATUS'
export const CHANGE_ANSWER_LOADING = 'CHANGE_ANSWER_LOADING'

export const SAVE_REQUEST = 'SAVE_REQUEST'
export const CHANGE_REQUEST_STATUS = 'CHANGE_REQUEST_STATUS'

export const SEND_REQUEST = 'SEND_REQUEST'
export const SEND_ACCOUNT_REQUEST = 'SEND_ACCOUNT_REQUEST'
export const SAVE_ACCOUNT_INFO = 'SAVE_ACCOUNT_INFO'

export const SAVE_REQUEST_HISTORY = 'SAVE_REQUEST_HISTORY'
export const DELETE_REQUEST_HISTORY = 'DELETE_REQUEST_HISTORY'
export const ERASE_REQUESTS_HISTORY = 'ERASE_REQUESTS_HISTORY'
export const SAVE_REQUEST_HISTORY_INITIAL = 'SAVE_REQUEST_HISTORY_INITIAL'

export const CHANGE_FORM_VALUE = 'CHANGE_FORM_VALUE'
export const CHANGE_INPUTS_VALIDATE = 'CHANGE_INPUTS_VALIDATE'
export const CHANGE_FORM_VALIDATE = 'CHANGE_FORM_VALIDATE'
export const CHANGE_SUBMIT_STATUS = 'CHANGE_SUBMIT_STATUS'
export const CHANGE_INVALID_STATUS = 'CHANGE_INVALID_STATUS'
export const CHANGE_FORM_ERROR_STATUS = 'CHANGE_FORM_ERROR_STATUS'
export const CHANGE_FORM_LOADING_STATUS = 'CHANGE_FORM_LOADING_STATUS'
export const SEND_AUTH_FORM = 'SEND_AUTH_FORM'